run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  disable:
    - exportloopref  # Deprecated since Go 1.22
    - tenv           # Deprecated, replaced by usetesting

  enable:
    # Critical linters
    - errcheck      # Check for unchecked errors (important!)
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code

    # Code quality
    - gofmt         # Check formatting
    - gofumpt       # Stricter gofmt
    - goimports     # Check imports formatting
    - misspell      # Find commonly misspelled words
    - unconvert     # Unnecessary type conversions
    - gocyclo       # Cyclomatic complexity
    - bodyclose     # Check HTTP response bodies are closed
    - nolintlint    # Ill-formed or insufficient nolint directives
    - rowserrcheck  # Check database/sql rows.Err
    - sqlclosecheck # Check sql.Rows and sql.Stmt are closed
    - typecheck     # Type check
    - whitespace    # Detect leading/trailing whitespace
    - copyloopvar   # Replace exportloopref
    - usetesting    # Replace tenv

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - errorsas
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult

  gocyclo:
    min-complexity: 20

  misspell:
    locale: US

  goimports:
    local-prefixes: linux-iso-manager

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude known false positives
    - path: internal/api/directory\.go
      linters:
        - gosec  # G307: Deferring unsafe method

    # Allow long lines in generated files
    - path: migrations/
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
